package cloud

// RegisterAlibabaServices adds Alibaba Cloud services to the knowledge base.
func RegisterAlibabaServices(kb *ServiceKnowledgeBase) {
	kb.Add(CloudService{
		Name:         "ECS",
		Provider:     Alibaba,
		Category:     CatCompute,
		Description:  "Elastic Compute Service — scalable virtual machines",
		UseCases:     []string{"web servers", "enterprise apps", "batch processing", "dev/test"},
		AntiPatterns: []string{"event-driven workloads (use Function Compute)", "over-provisioning"},
		PricingModel: "per-hour",
		FreeTier:     "Free trial available for new users",
		Equivalents:  map[CloudProvider]string{AWS: "EC2", GCP: "Compute Engine", Azure: "Virtual Machines"},
		Tags:         []string{"vm", "compute", "instances"},
	})
	kb.Add(CloudService{
		Name:         "Function Compute",
		Provider:     Alibaba,
		Category:     CatServerless,
		Description:  "Event-driven serverless compute platform",
		UseCases:     []string{"API backends", "event processing", "IoT triggers", "data processing"},
		AntiPatterns: []string{"long-running processes", "stateful workloads"},
		PricingModel: "per-request",
		FreeTier:     "1M requests/month for free",
		Equivalents:  map[CloudProvider]string{AWS: "Lambda", GCP: "Cloud Functions", Azure: "Azure Functions"},
		Tags:         []string{"serverless", "functions", "faas"},
	})
	kb.Add(CloudService{
		Name:         "OSS",
		Provider:     Alibaba,
		Category:     CatStorage,
		Description:  "Object Storage Service — scalable cloud storage",
		UseCases:     []string{"data lake", "backups", "static hosting", "media storage"},
		AntiPatterns: []string{"using as a database", "frequent tiny random reads"},
		PricingModel: "per-gb",
		FreeTier:     "5 GB standard storage",
		Equivalents:  map[CloudProvider]string{AWS: "S3", GCP: "Cloud Storage", Azure: "Blob Storage"},
		Tags:         []string{"storage", "object", "blob"},
	})
	kb.Add(CloudService{
		Name:         "ApsaraDB RDS",
		Provider:     Alibaba,
		Category:     CatDatabase,
		Description:  "Managed relational database — MySQL, PostgreSQL, SQL Server",
		UseCases:     []string{"web applications", "OLTP workloads", "enterprise systems"},
		AntiPatterns: []string{"analytics (use MaxCompute)", "NoSQL workloads"},
		PricingModel: "per-hour",
		FreeTier:     "Free trial for new users",
		Equivalents:  map[CloudProvider]string{AWS: "RDS", GCP: "Cloud SQL", Azure: "Azure SQL"},
		Tags:         []string{"database", "sql", "relational", "mysql", "postgres"},
	})
	kb.Add(CloudService{
		Name:         "PolarDB",
		Provider:     Alibaba,
		Category:     CatDatabase,
		Description:  "Cloud-native distributed relational database",
		UseCases:     []string{"high-performance OLTP", "large-scale SaaS", "financial systems"},
		AntiPatterns: []string{"small workloads where RDS suffices", "non-relational data"},
		PricingModel: "per-hour",
		FreeTier:     "",
		Equivalents:  map[CloudProvider]string{AWS: "Aurora", GCP: "Spanner", Azure: "Cosmos DB"},
		Tags:         []string{"database", "sql", "distributed", "cloud-native"},
	})
	kb.Add(CloudService{
		Name:         "Tair",
		Provider:     Alibaba,
		Category:     CatDatabase,
		Description:  "Redis-compatible in-memory database with persistence",
		UseCases:     []string{"caching", "session management", "real-time analytics", "leaderboards"},
		AntiPatterns: []string{"primary persistent storage", "complex queries"},
		PricingModel: "per-hour",
		FreeTier:     "",
		Equivalents:  map[CloudProvider]string{AWS: "ElastiCache", GCP: "Memorystore", Azure: "Cache for Redis"},
		Tags:         []string{"cache", "redis", "in-memory"},
	})
	kb.Add(CloudService{
		Name:         "ACK",
		Provider:     Alibaba,
		Category:     CatContainers,
		Description:  "Alibaba Cloud Container Service for Kubernetes",
		UseCases:     []string{"microservices", "hybrid cloud", "CI/CD", "batch processing"},
		AntiPatterns: []string{"simple apps (use SAE)", "no K8s expertise"},
		PricingModel: "per-hour",
		FreeTier:     "Free cluster management",
		Equivalents:  map[CloudProvider]string{AWS: "EKS", GCP: "GKE", Azure: "AKS"},
		Tags:         []string{"kubernetes", "k8s", "containers", "orchestration"},
	})
	kb.Add(CloudService{
		Name:         "SAE",
		Provider:     Alibaba,
		Category:     CatContainers,
		Description:  "Serverless App Engine — serverless container platform",
		UseCases:     []string{"microservices", "web apps", "batch jobs"},
		AntiPatterns: []string{"full K8s API needed (use ACK)", "GPU workloads"},
		PricingModel: "per-request",
		FreeTier:     "",
		Equivalents:  map[CloudProvider]string{AWS: "ECS", GCP: "Cloud Run", Azure: "Container Apps"},
		Tags:         []string{"serverless", "containers"},
	})
	kb.Add(CloudService{
		Name:         "API Gateway",
		Provider:     Alibaba,
		Category:     CatNetworking,
		Description:  "API lifecycle management and gateway",
		UseCases:     []string{"API publishing", "rate limiting", "authentication", "monitoring"},
		AntiPatterns: []string{"simple internal routing"},
		PricingModel: "per-request",
		FreeTier:     "1M calls/month",
		Equivalents:  map[CloudProvider]string{AWS: "API Gateway", GCP: "Apigee", Azure: "API Management"},
		Tags:         []string{"api", "gateway", "management"},
	})
	kb.Add(CloudService{
		Name:         "CDN",
		Provider:     Alibaba,
		Category:     CatNetworking,
		Description:  "Content delivery network with global edge nodes",
		UseCases:     []string{"static content", "video streaming", "download acceleration"},
		AntiPatterns: []string{"dynamic content without cache strategy"},
		PricingModel: "per-gb",
		FreeTier:     "",
		Equivalents:  map[CloudProvider]string{AWS: "CloudFront", GCP: "Cloud CDN", Azure: "Azure CDN"},
		Tags:         []string{"cdn", "content-delivery", "edge"},
	})
	kb.Add(CloudService{
		Name:         "DNS",
		Provider:     Alibaba,
		Category:     CatNetworking,
		Description:  "Alibaba Cloud DNS resolution service",
		UseCases:     []string{"domain management", "DNS routing", "global traffic management"},
		AntiPatterns: []string{"complex load balancing (use SLB)"},
		PricingModel: "per-request",
		FreeTier:     "Basic DNS free",
		Equivalents:  map[CloudProvider]string{AWS: "Route 53", GCP: "Cloud DNS", Azure: "Azure DNS"},
		Tags:         []string{"dns", "domain", "routing"},
	})
	kb.Add(CloudService{
		Name:         "VPC",
		Provider:     Alibaba,
		Category:     CatNetworking,
		Description:  "Virtual Private Cloud — logically isolated network",
		UseCases:     []string{"network isolation", "hybrid connectivity", "multi-tier architectures"},
		AntiPatterns: []string{"flat single subnet design"},
		PricingModel: "per-hour",
		FreeTier:     "VPC itself is free",
		Equivalents:  map[CloudProvider]string{AWS: "VPC", GCP: "VPC", Azure: "VNet"},
		Tags:         []string{"network", "vpc", "isolation"},
	})
	kb.Add(CloudService{
		Name:         "RAM",
		Provider:     Alibaba,
		Category:     CatIdentity,
		Description:  "Resource Access Management — identity and access control",
		UseCases:     []string{"user management", "role-based access", "cross-account access"},
		AntiPatterns: []string{"overly permissive policies", "using root account"},
		PricingModel: "per-unit",
		FreeTier:     "Always free",
		Equivalents:  map[CloudProvider]string{AWS: "IAM", GCP: "IAM", Azure: "Entra ID"},
		Tags:         []string{"identity", "access", "iam", "rbac"},
	})
	kb.Add(CloudService{
		Name:         "Message Queue",
		Provider:     Alibaba,
		Category:     CatMessaging,
		Description:  "Distributed message queue service (RocketMQ-based)",
		UseCases:     []string{"async decoupling", "order processing", "event streaming", "log collection"},
		AntiPatterns: []string{"simple notifications only", "tiny message volumes"},
		PricingModel: "per-request",
		FreeTier:     "",
		Equivalents:  map[CloudProvider]string{AWS: "SQS", GCP: "Pub/Sub", Azure: "Service Bus"},
		Tags:         []string{"messaging", "queue", "async", "rocketmq"},
	})
	kb.Add(CloudService{
		Name:         "MaxCompute",
		Provider:     Alibaba,
		Category:     CatAnalytics,
		Description:  "Serverless data warehousing and large-scale analytics",
		UseCases:     []string{"data warehousing", "batch analytics", "BI reporting", "ETL"},
		AntiPatterns: []string{"OLTP workloads", "real-time queries"},
		PricingModel: "per-gb",
		FreeTier:     "",
		Equivalents:  map[CloudProvider]string{AWS: "Redshift", GCP: "BigQuery", Azure: "Synapse"},
		Tags:         []string{"analytics", "data-warehouse", "bi"},
	})
	kb.Add(CloudService{
		Name:         "DashScope",
		Provider:     Alibaba,
		Category:     CatAI_ML,
		Description:  "AI model service platform with Qwen and other foundation models",
		UseCases:     []string{"generative AI", "NLP", "computer vision", "multimodal AI"},
		AntiPatterns: []string{"custom model training at scale", "non-AI workloads"},
		PricingModel: "per-request",
		FreeTier:     "Free trial credits",
		Equivalents:  map[CloudProvider]string{AWS: "Bedrock", GCP: "Vertex AI", Azure: "Azure OpenAI"},
		Tags:         []string{"ai", "llm", "generative-ai", "qwen"},
	})
	kb.Add(CloudService{
		Name:         "CloudMonitor",
		Provider:     Alibaba,
		Category:     CatMonitoring,
		Description:  "Infrastructure and service monitoring platform",
		UseCases:     []string{"resource monitoring", "alerting", "custom metrics", "event monitoring"},
		AntiPatterns: []string{"deep APM (use ARMS)"},
		PricingModel: "per-unit",
		FreeTier:     "Basic monitoring free",
		Equivalents:  map[CloudProvider]string{AWS: "CloudWatch", GCP: "Cloud Monitoring", Azure: "Azure Monitor"},
		Tags:         []string{"monitoring", "observability", "metrics", "alerting"},
	})
	kb.Add(CloudService{
		Name:         "ARMS",
		Provider:     Alibaba,
		Category:     CatDevTools,
		Description:  "Application Real-Time Monitoring Service — APM and tracing",
		UseCases:     []string{"application monitoring", "distributed tracing", "alerting", "dashboards"},
		AntiPatterns: []string{"infrastructure-only monitoring (use CloudMonitor)"},
		PricingModel: "per-unit",
		FreeTier:     "Free edition available",
		Equivalents:  map[CloudProvider]string{AWS: "CodePipeline", GCP: "Cloud Build", Azure: "Azure DevOps"},
		Tags:         []string{"apm", "monitoring", "tracing", "devtools"},
	})
	kb.Add(CloudService{
		Name:         "KMS",
		Provider:     Alibaba,
		Category:     CatSecurity,
		Description:  "Key Management Service — encryption key and secret management",
		UseCases:     []string{"data encryption", "secret management", "key rotation"},
		AntiPatterns: []string{"application configuration (not secrets)"},
		PricingModel: "per-request",
		FreeTier:     "20 keys free",
		Equivalents:  map[CloudProvider]string{AWS: "KMS", GCP: "Cloud KMS", Azure: "Key Vault"},
		Tags:         []string{"security", "encryption", "keys", "secrets"},
	})
	kb.Add(CloudService{
		Name:         "Web App Firewall",
		Provider:     Alibaba,
		Category:     CatSecurity,
		Description:  "Web application firewall protecting against common exploits",
		UseCases:     []string{"SQL injection protection", "XSS prevention", "bot mitigation"},
		AntiPatterns: []string{"network-level firewall replacement"},
		PricingModel: "per-unit",
		FreeTier:     "",
		Equivalents:  map[CloudProvider]string{AWS: "WAF", GCP: "Cloud Armor", Azure: "Azure Firewall"},
		Tags:         []string{"security", "waf", "firewall", "web-protection"},
	})
}
