package cloud

// RegisterGCPServices adds GCP services to the knowledge base.
func RegisterGCPServices(kb *ServiceKnowledgeBase) {
	kb.Add(CloudService{
		Name:         "Compute Engine",
		Provider:     GCP,
		Category:     CatCompute,
		Description:  "Virtual machines running on Google infrastructure",
		UseCases:     []string{"web servers", "batch processing", "HPC", "custom OS images"},
		AntiPatterns: []string{"stateless event-driven workloads (use Cloud Functions)", "over-provisioning"},
		PricingModel: "per-hour",
		FreeTier:     "1 e2-micro instance/month (us regions)",
		Equivalents:  map[CloudProvider]string{AWS: "EC2", Azure: "Virtual Machines", Alibaba: "ECS"},
		Tags:         []string{"vm", "compute", "instances"},
	})
	kb.Add(CloudService{
		Name:         "Cloud Functions",
		Provider:     GCP,
		Category:     CatServerless,
		Description:  "Event-driven serverless functions",
		UseCases:     []string{"HTTP APIs", "event processing", "webhooks", "lightweight ETL"},
		AntiPatterns: []string{"long-running processes", "stateful workloads"},
		PricingModel: "per-request",
		FreeTier:     "2M invocations/month",
		Equivalents:  map[CloudProvider]string{AWS: "Lambda", Azure: "Azure Functions", Alibaba: "Function Compute"},
		Tags:         []string{"serverless", "functions", "faas"},
	})
	kb.Add(CloudService{
		Name:         "Cloud Storage",
		Provider:     GCP,
		Category:     CatStorage,
		Description:  "Unified object storage with multiple storage classes",
		UseCases:     []string{"data lake", "backups", "static hosting", "media storage"},
		AntiPatterns: []string{"using as a file system", "frequent small reads (use Filestore)"},
		PricingModel: "per-gb",
		FreeTier:     "5 GB-months standard storage",
		Equivalents:  map[CloudProvider]string{AWS: "S3", Azure: "Blob Storage", Alibaba: "OSS"},
		Tags:         []string{"storage", "object", "blob"},
	})
	kb.Add(CloudService{
		Name:         "Cloud SQL",
		Provider:     GCP,
		Category:     CatDatabase,
		Description:  "Managed MySQL, PostgreSQL, and SQL Server",
		UseCases:     []string{"web applications", "OLTP workloads", "CMS backends"},
		AntiPatterns: []string{"analytics workloads (use BigQuery)", "global distribution (use Spanner)"},
		PricingModel: "per-hour",
		FreeTier:     "db-f1-micro instance free tier",
		Equivalents:  map[CloudProvider]string{AWS: "RDS", Azure: "Azure SQL", Alibaba: "ApsaraDB RDS"},
		Tags:         []string{"database", "sql", "relational", "mysql", "postgres"},
	})
	kb.Add(CloudService{
		Name:         "Spanner",
		Provider:     GCP,
		Category:     CatDatabase,
		Description:  "Globally distributed, strongly consistent relational database",
		UseCases:     []string{"global OLTP", "financial systems", "inventory management"},
		AntiPatterns: []string{"small single-region workloads", "cost-sensitive projects"},
		PricingModel: "per-hour",
		FreeTier:     "90-day free trial instance",
		Equivalents:  map[CloudProvider]string{AWS: "Aurora", Azure: "Cosmos DB", Alibaba: "PolarDB"},
		Tags:         []string{"database", "sql", "global", "distributed"},
	})
	kb.Add(CloudService{
		Name:         "Firestore",
		Provider:     GCP,
		Category:     CatDatabase,
		Description:  "Serverless NoSQL document database with real-time sync",
		UseCases:     []string{"mobile/web backends", "real-time collaboration", "user profiles"},
		AntiPatterns: []string{"complex aggregations", "high-write throughput analytics"},
		PricingModel: "per-request",
		FreeTier:     "1 GiB storage, 50K reads/day",
		Equivalents:  map[CloudProvider]string{AWS: "DynamoDB", Azure: "Cosmos DB"},
		Tags:         []string{"database", "nosql", "document", "real-time"},
	})
	kb.Add(CloudService{
		Name:         "Bigtable",
		Provider:     GCP,
		Category:     CatDatabase,
		Description:  "Wide-column NoSQL database for large analytical and operational workloads",
		UseCases:     []string{"time-series data", "IoT telemetry", "ad-tech", "financial data"},
		AntiPatterns: []string{"small datasets", "complex queries with joins"},
		PricingModel: "per-hour",
		FreeTier:     "",
		Equivalents:  map[CloudProvider]string{AWS: "DynamoDB", Azure: "Cosmos DB"},
		Tags:         []string{"database", "nosql", "wide-column", "time-series"},
	})
	kb.Add(CloudService{
		Name:         "Memorystore",
		Provider:     GCP,
		Category:     CatDatabase,
		Description:  "Managed Redis and Memcached in-memory data store",
		UseCases:     []string{"caching", "session management", "real-time leaderboards"},
		AntiPatterns: []string{"persistent primary storage", "large datasets exceeding memory"},
		PricingModel: "per-hour",
		FreeTier:     "",
		Equivalents:  map[CloudProvider]string{AWS: "ElastiCache", Azure: "Cache for Redis", Alibaba: "Tair"},
		Tags:         []string{"cache", "redis", "memcached", "in-memory"},
	})
	kb.Add(CloudService{
		Name:         "GKE",
		Provider:     GCP,
		Category:     CatContainers,
		Description:  "Google Kubernetes Engine — managed Kubernetes",
		UseCases:     []string{"containerized microservices", "hybrid cloud", "ML training pipelines"},
		AntiPatterns: []string{"single-container apps (use Cloud Run)", "teams without K8s expertise"},
		PricingModel: "per-hour",
		FreeTier:     "1 Autopilot or zonal cluster free (management fee waived)",
		Equivalents:  map[CloudProvider]string{AWS: "EKS", Azure: "AKS", Alibaba: "ACK"},
		Tags:         []string{"kubernetes", "k8s", "containers", "orchestration"},
	})
	kb.Add(CloudService{
		Name:         "Cloud Run",
		Provider:     GCP,
		Category:     CatContainers,
		Description:  "Serverless container platform — deploy any container",
		UseCases:     []string{"stateless APIs", "web apps", "background workers", "event processing"},
		AntiPatterns: []string{"stateful workloads", "GPU-intensive jobs", "long WebSocket connections"},
		PricingModel: "per-request",
		FreeTier:     "2M requests/month, 360K vCPU-seconds",
		Equivalents:  map[CloudProvider]string{AWS: "ECS", Azure: "Container Apps", Alibaba: "SAE"},
		Tags:         []string{"serverless", "containers", "cloud-run"},
	})
	kb.Add(CloudService{
		Name:         "Apigee",
		Provider:     GCP,
		Category:     CatNetworking,
		Description:  "Full lifecycle API management platform",
		UseCases:     []string{"API monetization", "partner APIs", "API analytics", "developer portals"},
		AntiPatterns: []string{"simple internal routing (use Cloud Endpoints)", "cost-sensitive projects"},
		PricingModel: "per-request",
		FreeTier:     "Evaluation org available",
		Equivalents:  map[CloudProvider]string{AWS: "API Gateway", Azure: "API Management", Alibaba: "API Gateway"},
		Tags:         []string{"api", "gateway", "management"},
	})
	kb.Add(CloudService{
		Name:         "Cloud CDN",
		Provider:     GCP,
		Category:     CatNetworking,
		Description:  "Content delivery network leveraging Google's edge network",
		UseCases:     []string{"static content", "media delivery", "low-latency APIs"},
		AntiPatterns: []string{"dynamic personalized content without proper cache keys"},
		PricingModel: "per-gb",
		FreeTier:     "",
		Equivalents:  map[CloudProvider]string{AWS: "CloudFront", Azure: "Azure CDN", Alibaba: "CDN"},
		Tags:         []string{"cdn", "content-delivery", "edge"},
	})
	kb.Add(CloudService{
		Name:         "Cloud DNS",
		Provider:     GCP,
		Category:     CatNetworking,
		Description:  "Scalable, reliable, and managed DNS service",
		UseCases:     []string{"domain management", "DNS routing", "private DNS zones"},
		AntiPatterns: []string{"complex traffic management (use Cloud Load Balancing)"},
		PricingModel: "per-request",
		FreeTier:     "",
		Equivalents:  map[CloudProvider]string{AWS: "Route 53", Azure: "Azure DNS", Alibaba: "DNS"},
		Tags:         []string{"dns", "domain", "routing"},
	})
	kb.Add(CloudService{
		Name:         "VPC",
		Provider:     GCP,
		Category:     CatNetworking,
		Description:  "Global Virtual Private Cloud network",
		UseCases:     []string{"network isolation", "hybrid connectivity", "shared VPC for multi-project"},
		AntiPatterns: []string{"overly complex firewall rules", "single flat network for everything"},
		PricingModel: "per-hour",
		FreeTier:     "VPC itself is free; egress and NAT cost",
		Equivalents:  map[CloudProvider]string{AWS: "VPC", Azure: "VNet", Alibaba: "VPC"},
		Tags:         []string{"network", "vpc", "isolation"},
	})
	kb.Add(CloudService{
		Name:         "IAM",
		Provider:     GCP,
		Category:     CatIdentity,
		Description:  "Identity and Access Management for GCP resources",
		UseCases:     []string{"access control", "service accounts", "workload identity", "organization policies"},
		AntiPatterns: []string{"overly broad roles", "using user accounts for automation"},
		PricingModel: "per-unit",
		FreeTier:     "Always free",
		Equivalents:  map[CloudProvider]string{AWS: "IAM", Azure: "Entra ID", Alibaba: "RAM"},
		Tags:         []string{"identity", "access", "iam", "rbac"},
	})
	kb.Add(CloudService{
		Name:         "Pub/Sub",
		Provider:     GCP,
		Category:     CatMessaging,
		Description:  "Global real-time messaging and event ingestion",
		UseCases:     []string{"event-driven architectures", "stream processing", "async communication"},
		AntiPatterns: []string{"guaranteed ordering (use Pub/Sub Lite)", "very large messages"},
		PricingModel: "per-gb",
		FreeTier:     "10 GB/month",
		Equivalents:  map[CloudProvider]string{AWS: "SQS", Azure: "Service Bus", Alibaba: "Message Queue"},
		Tags:         []string{"messaging", "pubsub", "streaming", "events"},
	})
	kb.Add(CloudService{
		Name:         "Dataflow",
		Provider:     GCP,
		Category:     CatAnalytics,
		Description:  "Unified stream and batch data processing (Apache Beam)",
		UseCases:     []string{"ETL pipelines", "real-time analytics", "log processing"},
		AntiPatterns: []string{"simple batch SQL (use BigQuery)", "small datasets"},
		PricingModel: "per-hour",
		FreeTier:     "",
		Equivalents:  map[CloudProvider]string{AWS: "Kinesis", Azure: "Event Hubs"},
		Tags:         []string{"analytics", "streaming", "batch", "etl"},
	})
	kb.Add(CloudService{
		Name:         "BigQuery",
		Provider:     GCP,
		Category:     CatAnalytics,
		Description:  "Serverless, multi-cloud data warehouse",
		UseCases:     []string{"business intelligence", "ad-hoc analytics", "ML training data", "log analysis"},
		AntiPatterns: []string{"OLTP workloads", "sub-second latency queries", "small datasets"},
		PricingModel: "per-gb",
		FreeTier:     "1 TB queries/month, 10 GB storage",
		Equivalents:  map[CloudProvider]string{AWS: "Redshift", Azure: "Synapse", Alibaba: "MaxCompute"},
		Tags:         []string{"analytics", "data-warehouse", "sql", "bi"},
	})
	kb.Add(CloudService{
		Name:         "Vertex AI",
		Provider:     GCP,
		Category:     CatAI_ML,
		Description:  "Unified ML platform for building, deploying, and scaling models",
		UseCases:     []string{"model training", "AutoML", "prediction serving", "generative AI"},
		AntiPatterns: []string{"simple LLM API calls (use AI Studio)", "non-ML compute"},
		PricingModel: "per-hour",
		FreeTier:     "$300 free credits for new accounts",
		Equivalents:  map[CloudProvider]string{AWS: "SageMaker", Azure: "Azure OpenAI", Alibaba: "DashScope"},
		Tags:         []string{"ml", "ai", "training", "inference", "generative-ai"},
	})
	kb.Add(CloudService{
		Name:         "Cloud Monitoring",
		Provider:     GCP,
		Category:     CatMonitoring,
		Description:  "Infrastructure and application monitoring with metrics and alerting",
		UseCases:     []string{"resource monitoring", "uptime checks", "custom metrics", "SLO tracking"},
		AntiPatterns: []string{"deep APM tracing (use Cloud Trace)", "log-only analysis (use Cloud Logging)"},
		PricingModel: "per-unit",
		FreeTier:     "All GCP metrics free; custom metrics charged",
		Equivalents:  map[CloudProvider]string{AWS: "CloudWatch", Azure: "Azure Monitor", Alibaba: "CloudMonitor"},
		Tags:         []string{"monitoring", "observability", "metrics", "alerting"},
	})
	kb.Add(CloudService{
		Name:         "Cloud Build",
		Provider:     GCP,
		Category:     CatDevTools,
		Description:  "Serverless CI/CD platform",
		UseCases:     []string{"container builds", "CI/CD pipelines", "automated testing"},
		AntiPatterns: []string{"complex multi-stage release management (use Spinnaker)"},
		PricingModel: "per-unit",
		FreeTier:     "120 build-minutes/day",
		Equivalents:  map[CloudProvider]string{AWS: "CodePipeline", Azure: "Azure DevOps", Alibaba: "ARMS"},
		Tags:         []string{"ci-cd", "devops", "build", "pipeline"},
	})
	kb.Add(CloudService{
		Name:         "Eventarc",
		Provider:     GCP,
		Category:     CatServerless,
		Description:  "Event-driven architecture for Cloud Run and GKE",
		UseCases:     []string{"event routing", "async processing", "workflow triggers"},
		AntiPatterns: []string{"high-throughput streaming (use Pub/Sub)", "synchronous calls"},
		PricingModel: "per-request",
		FreeTier:     "Included with Cloud Run",
		Equivalents:  map[CloudProvider]string{AWS: "EventBridge", Azure: "Event Grid"},
		Tags:         []string{"events", "serverless", "integration"},
	})
	kb.Add(CloudService{
		Name:         "Secret Manager",
		Provider:     GCP,
		Category:     CatSecurity,
		Description:  "Store and manage API keys, passwords, and certificates",
		UseCases:     []string{"secret storage", "credential rotation", "certificate management"},
		AntiPatterns: []string{"large config files", "non-sensitive configuration"},
		PricingModel: "per-unit",
		FreeTier:     "6 active secret versions",
		Equivalents:  map[CloudProvider]string{AWS: "Secrets Manager", Azure: "Key Vault", Alibaba: "KMS"},
		Tags:         []string{"security", "secrets", "credentials"},
	})
	kb.Add(CloudService{
		Name:         "Cloud KMS",
		Provider:     GCP,
		Category:     CatSecurity,
		Description:  "Cloud Key Management Service for encryption key lifecycle",
		UseCases:     []string{"encryption at rest", "envelope encryption", "signing"},
		AntiPatterns: []string{"secret storage (use Secret Manager)"},
		PricingModel: "per-request",
		FreeTier:     "",
		Equivalents:  map[CloudProvider]string{AWS: "KMS", Azure: "Key Vault", Alibaba: "KMS"},
		Tags:         []string{"security", "encryption", "keys", "kms"},
	})
	kb.Add(CloudService{
		Name:         "Cloud Armor",
		Provider:     GCP,
		Category:     CatSecurity,
		Description:  "DDoS protection and WAF for Google Cloud resources",
		UseCases:     []string{"DDoS mitigation", "WAF rules", "geo-blocking", "bot management"},
		AntiPatterns: []string{"application-level auth (use IAP)"},
		PricingModel: "per-request",
		FreeTier:     "",
		Equivalents:  map[CloudProvider]string{AWS: "WAF", Azure: "Azure Firewall", Alibaba: "Web App Firewall"},
		Tags:         []string{"security", "waf", "ddos", "firewall"},
	})
	kb.Add(CloudService{
		Name:         "Cloud Workflows",
		Provider:     GCP,
		Category:     CatServerless,
		Description:  "Serverless workflow orchestration for GCP and HTTP services",
		UseCases:     []string{"microservice orchestration", "API composition", "batch job coordination"},
		AntiPatterns: []string{"high-frequency low-latency pipelines", "complex state machines"},
		PricingModel: "per-request",
		FreeTier:     "5000 steps/month",
		Equivalents:  map[CloudProvider]string{AWS: "Step Functions", Azure: "Logic Apps"},
		Tags:         []string{"workflow", "orchestration", "serverless"},
	})
	kb.Add(CloudService{
		Name:         "Security Command Center",
		Provider:     GCP,
		Category:     CatSecurity,
		Description:  "Security and risk management platform for GCP",
		UseCases:     []string{"vulnerability scanning", "compliance monitoring", "threat detection"},
		AntiPatterns: []string{"application-level security testing"},
		PricingModel: "per-unit",
		FreeTier:     "Standard tier included",
		Equivalents:  map[CloudProvider]string{AWS: "GuardDuty", Azure: "Microsoft Defender"},
		Tags:         []string{"security", "compliance", "threat-detection"},
	})
}
