package cloud

// RegisterAzureServices adds Azure services to the knowledge base.
func RegisterAzureServices(kb *ServiceKnowledgeBase) {
	kb.Add(CloudService{
		Name:         "Virtual Machines",
		Provider:     Azure,
		Category:     CatCompute,
		Description:  "On-demand scalable virtual machines",
		UseCases:     []string{"web servers", "enterprise apps", "dev/test", "HPC"},
		AntiPatterns: []string{"stateless event-driven workloads (use Azure Functions)", "over-provisioning"},
		PricingModel: "per-hour",
		FreeTier:     "750 hrs/month B1S for 12 months",
		Equivalents:  map[CloudProvider]string{AWS: "EC2", GCP: "Compute Engine", Alibaba: "ECS"},
		Tags:         []string{"vm", "compute", "instances"},
	})
	kb.Add(CloudService{
		Name:         "Azure Functions",
		Provider:     Azure,
		Category:     CatServerless,
		Description:  "Event-driven serverless compute",
		UseCases:     []string{"API backends", "event processing", "scheduled jobs", "IoT processing"},
		AntiPatterns: []string{"long-running processes >10min", "stateful workflows (use Durable Functions)"},
		PricingModel: "per-request",
		FreeTier:     "1M requests/month always free",
		Equivalents:  map[CloudProvider]string{AWS: "Lambda", GCP: "Cloud Functions", Alibaba: "Function Compute"},
		Tags:         []string{"serverless", "functions", "faas"},
	})
	kb.Add(CloudService{
		Name:         "Blob Storage",
		Provider:     Azure,
		Category:     CatStorage,
		Description:  "Massively scalable object storage with tiered access",
		UseCases:     []string{"data lake", "backups", "static websites", "media storage"},
		AntiPatterns: []string{"using as a database", "frequent random access patterns"},
		PricingModel: "per-gb",
		FreeTier:     "5 GB LRS hot storage for 12 months",
		Equivalents:  map[CloudProvider]string{AWS: "S3", GCP: "Cloud Storage", Alibaba: "OSS"},
		Tags:         []string{"storage", "object", "blob"},
	})
	kb.Add(CloudService{
		Name:         "Azure SQL",
		Provider:     Azure,
		Category:     CatDatabase,
		Description:  "Managed SQL Server database with built-in intelligence",
		UseCases:     []string{"enterprise OLTP", "SaaS applications", ".NET backends"},
		AntiPatterns: []string{"non-SQL workloads", "PostgreSQL/MySQL needs (use Azure Database for)"},
		PricingModel: "per-hour",
		FreeTier:     "100K vCore-seconds/month always free (serverless)",
		Equivalents:  map[CloudProvider]string{AWS: "RDS", GCP: "Cloud SQL", Alibaba: "ApsaraDB RDS"},
		Tags:         []string{"database", "sql", "relational", "sql-server"},
	})
	kb.Add(CloudService{
		Name:         "Cosmos DB",
		Provider:     Azure,
		Category:     CatDatabase,
		Description:  "Globally distributed multi-model NoSQL database",
		UseCases:     []string{"global apps", "IoT", "real-time personalization", "gaming"},
		AntiPatterns: []string{"simple single-region SQL (use Azure SQL)", "cost-sensitive analytics"},
		PricingModel: "per-request",
		FreeTier:     "1000 RU/s, 25 GB storage always free",
		Equivalents:  map[CloudProvider]string{AWS: "DynamoDB", GCP: "Firestore", Alibaba: "PolarDB"},
		Tags:         []string{"database", "nosql", "global", "multi-model"},
	})
	kb.Add(CloudService{
		Name:         "Cache for Redis",
		Provider:     Azure,
		Category:     CatDatabase,
		Description:  "Managed Redis caching service",
		UseCases:     []string{"session caching", "real-time analytics", "message broker"},
		AntiPatterns: []string{"persistent primary storage", "datasets exceeding available memory"},
		PricingModel: "per-hour",
		FreeTier:     "",
		Equivalents:  map[CloudProvider]string{AWS: "ElastiCache", GCP: "Memorystore", Alibaba: "Tair"},
		Tags:         []string{"cache", "redis", "in-memory"},
	})
	kb.Add(CloudService{
		Name:         "AKS",
		Provider:     Azure,
		Category:     CatContainers,
		Description:  "Azure Kubernetes Service — managed Kubernetes",
		UseCases:     []string{"microservices", "hybrid cloud", "ML workloads", "multi-cloud"},
		AntiPatterns: []string{"simple single-container apps (use Container Apps)", "no K8s expertise"},
		PricingModel: "per-hour",
		FreeTier:     "Free cluster management (pay for nodes only)",
		Equivalents:  map[CloudProvider]string{AWS: "EKS", GCP: "GKE", Alibaba: "ACK"},
		Tags:         []string{"kubernetes", "k8s", "containers", "orchestration"},
	})
	kb.Add(CloudService{
		Name:         "Container Apps",
		Provider:     Azure,
		Category:     CatContainers,
		Description:  "Serverless container hosting with auto-scaling",
		UseCases:     []string{"microservices", "APIs", "background workers", "event-driven apps"},
		AntiPatterns: []string{"full K8s API needed (use AKS)", "GPU workloads"},
		PricingModel: "per-request",
		FreeTier:     "180K vCPU-seconds, 360K GiB-seconds/month",
		Equivalents:  map[CloudProvider]string{AWS: "ECS", GCP: "Cloud Run", Alibaba: "SAE"},
		Tags:         []string{"serverless", "containers", "cloud-run"},
	})
	kb.Add(CloudService{
		Name:         "API Management",
		Provider:     Azure,
		Category:     CatNetworking,
		Description:  "Full lifecycle API management with developer portal",
		UseCases:     []string{"API gateway", "rate limiting", "API monetization", "documentation"},
		AntiPatterns: []string{"simple internal routing", "cost-sensitive small projects"},
		PricingModel: "per-unit",
		FreeTier:     "Developer tier for testing",
		Equivalents:  map[CloudProvider]string{AWS: "API Gateway", GCP: "Apigee", Alibaba: "API Gateway"},
		Tags:         []string{"api", "gateway", "management"},
	})
	kb.Add(CloudService{
		Name:         "Azure CDN",
		Provider:     Azure,
		Category:     CatNetworking,
		Description:  "Global content delivery network",
		UseCases:     []string{"static assets", "media streaming", "software distribution"},
		AntiPatterns: []string{"dynamic content without cache strategy"},
		PricingModel: "per-gb",
		FreeTier:     "",
		Equivalents:  map[CloudProvider]string{AWS: "CloudFront", GCP: "Cloud CDN", Alibaba: "CDN"},
		Tags:         []string{"cdn", "content-delivery", "edge"},
	})
	kb.Add(CloudService{
		Name:         "Azure DNS",
		Provider:     Azure,
		Category:     CatNetworking,
		Description:  "DNS hosting with ultra-fast responses",
		UseCases:     []string{"domain management", "private DNS zones", "DNS-based routing"},
		AntiPatterns: []string{"domain registration (use external registrar)"},
		PricingModel: "per-request",
		FreeTier:     "",
		Equivalents:  map[CloudProvider]string{AWS: "Route 53", GCP: "Cloud DNS", Alibaba: "DNS"},
		Tags:         []string{"dns", "domain", "routing"},
	})
	kb.Add(CloudService{
		Name:         "VNet",
		Provider:     Azure,
		Category:     CatNetworking,
		Description:  "Azure Virtual Network — isolated network environment",
		UseCases:     []string{"network isolation", "hybrid connectivity", "service endpoints"},
		AntiPatterns: []string{"flat network without segmentation"},
		PricingModel: "per-hour",
		FreeTier:     "VNet itself is free; peering and gateways cost",
		Equivalents:  map[CloudProvider]string{AWS: "VPC", GCP: "VPC", Alibaba: "VPC"},
		Tags:         []string{"network", "vnet", "isolation"},
	})
	kb.Add(CloudService{
		Name:         "Entra ID",
		Provider:     Azure,
		Category:     CatIdentity,
		Description:  "Identity platform (formerly Azure AD) — SSO, MFA, RBAC",
		UseCases:     []string{"enterprise SSO", "B2C identity", "conditional access", "MFA"},
		AntiPatterns: []string{"simple API key auth (overkill)", "non-Microsoft ecosystems only"},
		PricingModel: "per-unit",
		FreeTier:     "Free tier with 50K objects",
		Equivalents:  map[CloudProvider]string{AWS: "IAM", GCP: "IAM", Alibaba: "RAM"},
		Tags:         []string{"identity", "access", "sso", "mfa", "rbac"},
	})
	kb.Add(CloudService{
		Name:         "Service Bus",
		Provider:     Azure,
		Category:     CatMessaging,
		Description:  "Enterprise message broker with queues and topics",
		UseCases:     []string{"decoupling services", "ordered messaging", "sessions", "dead-lettering"},
		AntiPatterns: []string{"simple event notifications (use Event Grid)", "high-throughput streaming (use Event Hubs)"},
		PricingModel: "per-unit",
		FreeTier:     "",
		Equivalents:  map[CloudProvider]string{AWS: "SQS", GCP: "Pub/Sub", Alibaba: "Message Queue"},
		Tags:         []string{"messaging", "queue", "topics", "enterprise"},
	})
	kb.Add(CloudService{
		Name:         "Event Hubs",
		Provider:     Azure,
		Category:     CatAnalytics,
		Description:  "Big data streaming platform and event ingestion",
		UseCases:     []string{"telemetry ingestion", "log streaming", "real-time analytics"},
		AntiPatterns: []string{"small-scale messaging (use Service Bus)", "batch-only ETL"},
		PricingModel: "per-unit",
		FreeTier:     "",
		Equivalents:  map[CloudProvider]string{AWS: "Kinesis", GCP: "Dataflow", Alibaba: "Message Queue"},
		Tags:         []string{"streaming", "events", "analytics", "ingestion"},
	})
	kb.Add(CloudService{
		Name:         "Synapse",
		Provider:     Azure,
		Category:     CatAnalytics,
		Description:  "Unified analytics service combining data warehousing and big data",
		UseCases:     []string{"data warehousing", "big data analytics", "BI reporting", "data lake analytics"},
		AntiPatterns: []string{"OLTP workloads", "simple queries (use Azure SQL)"},
		PricingModel: "per-unit",
		FreeTier:     "",
		Equivalents:  map[CloudProvider]string{AWS: "Redshift", GCP: "BigQuery", Alibaba: "MaxCompute"},
		Tags:         []string{"analytics", "data-warehouse", "bi", "big-data"},
	})
	kb.Add(CloudService{
		Name:         "Azure OpenAI",
		Provider:     Azure,
		Category:     CatAI_ML,
		Description:  "Enterprise access to OpenAI models (GPT-4, DALL-E, Whisper)",
		UseCases:     []string{"generative AI apps", "content generation", "code assistance", "RAG"},
		AntiPatterns: []string{"custom model training (use Azure ML)", "non-AI compute"},
		PricingModel: "per-request",
		FreeTier:     "",
		Equivalents:  map[CloudProvider]string{AWS: "Bedrock", GCP: "Vertex AI", Alibaba: "DashScope"},
		Tags:         []string{"ai", "llm", "generative-ai", "openai"},
	})
	kb.Add(CloudService{
		Name:         "Azure Monitor",
		Provider:     Azure,
		Category:     CatMonitoring,
		Description:  "Full-stack monitoring — metrics, logs, traces, alerts",
		UseCases:     []string{"infrastructure monitoring", "application insights", "log analytics", "alerting"},
		AntiPatterns: []string{"simple uptime checks only (use availability tests)"},
		PricingModel: "per-gb",
		FreeTier:     "5 GB log ingestion/month",
		Equivalents:  map[CloudProvider]string{AWS: "CloudWatch", GCP: "Cloud Monitoring", Alibaba: "CloudMonitor"},
		Tags:         []string{"monitoring", "observability", "logs", "metrics"},
	})
	kb.Add(CloudService{
		Name:         "Azure DevOps",
		Provider:     Azure,
		Category:     CatDevTools,
		Description:  "CI/CD, repos, boards, test plans, and artifacts",
		UseCases:     []string{"CI/CD pipelines", "project management", "artifact hosting", "test management"},
		AntiPatterns: []string{"open-source projects (use GitHub Actions)", "non-Microsoft stacks only"},
		PricingModel: "per-unit",
		FreeTier:     "5 users free, 1 parallel CI/CD job",
		Equivalents:  map[CloudProvider]string{AWS: "CodePipeline", GCP: "Cloud Build", Alibaba: "ARMS"},
		Tags:         []string{"ci-cd", "devops", "pipeline", "repos"},
	})
	kb.Add(CloudService{
		Name:         "Event Grid",
		Provider:     Azure,
		Category:     CatServerless,
		Description:  "Serverless event routing service",
		UseCases:     []string{"event-driven architectures", "reactive programming", "serverless workflows"},
		AntiPatterns: []string{"guaranteed message ordering (use Service Bus)", "high-throughput streaming"},
		PricingModel: "per-request",
		FreeTier:     "100K operations/month",
		Equivalents:  map[CloudProvider]string{AWS: "EventBridge", GCP: "Eventarc"},
		Tags:         []string{"events", "serverless", "routing"},
	})
	kb.Add(CloudService{
		Name:         "Key Vault",
		Provider:     Azure,
		Category:     CatSecurity,
		Description:  "Safeguard keys, secrets, and certificates",
		UseCases:     []string{"secret management", "key management", "certificate lifecycle", "HSM-backed keys"},
		AntiPatterns: []string{"large config files", "application configuration (use App Configuration)"},
		PricingModel: "per-request",
		FreeTier:     "",
		Equivalents:  map[CloudProvider]string{AWS: "Secrets Manager", GCP: "Secret Manager", Alibaba: "KMS"},
		Tags:         []string{"security", "secrets", "keys", "certificates"},
	})
	kb.Add(CloudService{
		Name:         "Azure Firewall",
		Provider:     Azure,
		Category:     CatSecurity,
		Description:  "Cloud-native network firewall with threat intelligence",
		UseCases:     []string{"network security", "threat filtering", "FQDN filtering", "traffic inspection"},
		AntiPatterns: []string{"web application protection only (use WAF)", "simple NSG suffices"},
		PricingModel: "per-hour",
		FreeTier:     "",
		Equivalents:  map[CloudProvider]string{AWS: "WAF", GCP: "Cloud Armor", Alibaba: "Web App Firewall"},
		Tags:         []string{"security", "firewall", "network-protection"},
	})
	kb.Add(CloudService{
		Name:         "Front Door",
		Provider:     Azure,
		Category:     CatNetworking,
		Description:  "Global load balancer and CDN with WAF integration",
		UseCases:     []string{"global HTTP routing", "SSL offloading", "WAF at edge", "failover"},
		AntiPatterns: []string{"non-HTTP traffic (use Traffic Manager)", "single-region apps"},
		PricingModel: "per-request",
		FreeTier:     "",
		Equivalents:  map[CloudProvider]string{AWS: "CloudFront", GCP: "Cloud CDN"},
		Tags:         []string{"cdn", "load-balancer", "global", "edge"},
	})
	kb.Add(CloudService{
		Name:         "App Service",
		Provider:     Azure,
		Category:     CatCompute,
		Description:  "Managed platform for web apps, APIs, and mobile backends",
		UseCases:     []string{"web applications", "REST APIs", "mobile backends", "multi-language hosting"},
		AntiPatterns: []string{"heavy compute (use VMs)", "container-first approaches (use Container Apps)"},
		PricingModel: "per-hour",
		FreeTier:     "10 web apps with 1 GB storage",
		Equivalents:  map[CloudProvider]string{AWS: "Elastic Beanstalk", GCP: "App Engine"},
		Tags:         []string{"compute", "web", "paas", "hosting"},
	})
	kb.Add(CloudService{
		Name:         "Logic Apps",
		Provider:     Azure,
		Category:     CatServerless,
		Description:  "Low-code workflow automation with 400+ connectors",
		UseCases:     []string{"business process automation", "SaaS integration", "approval workflows", "data sync"},
		AntiPatterns: []string{"high-performance compute", "complex custom logic (use Azure Functions)"},
		PricingModel: "per-request",
		FreeTier:     "",
		Equivalents:  map[CloudProvider]string{AWS: "Step Functions", GCP: "Cloud Workflows"},
		Tags:         []string{"workflow", "automation", "low-code", "integration"},
	})
	kb.Add(CloudService{
		Name:         "Microsoft Defender",
		Provider:     Azure,
		Category:     CatSecurity,
		Description:  "Cloud-native security posture management and threat protection",
		UseCases:     []string{"security posture", "threat detection", "compliance", "vulnerability assessment"},
		AntiPatterns: []string{"replacing dedicated SIEM", "non-Azure workloads only"},
		PricingModel: "per-unit",
		FreeTier:     "Free tier with limited features",
		Equivalents:  map[CloudProvider]string{AWS: "GuardDuty", GCP: "Security Command Center"},
		Tags:         []string{"security", "threat-detection", "compliance"},
	})
}
