package cloud

// RegisterAWSServices adds AWS services to the knowledge base.
func RegisterAWSServices(kb *ServiceKnowledgeBase) {
	kb.Add(CloudService{
		Name:         "EC2",
		Provider:     AWS,
		Category:     CatCompute,
		Description:  "Elastic Compute Cloud — resizable virtual machines",
		UseCases:     []string{"web servers", "batch processing", "HPC", "dev/test environments"},
		AntiPatterns: []string{"using for stateless workloads better suited to Lambda", "over-provisioning instance sizes"},
		PricingModel: "per-hour",
		FreeTier:     "750 hrs/month t2.micro for 12 months",
		Equivalents:  map[CloudProvider]string{GCP: "Compute Engine", Azure: "Virtual Machines", Alibaba: "ECS"},
		Tags:         []string{"vm", "compute", "instances"},
	})
	kb.Add(CloudService{
		Name:         "Lambda",
		Provider:     AWS,
		Category:     CatServerless,
		Description:  "Serverless compute — run code without provisioning servers",
		UseCases:     []string{"event-driven processing", "API backends", "data transformation", "scheduled tasks"},
		AntiPatterns: []string{"long-running processes >15min", "high-throughput constant workloads"},
		PricingModel: "per-request",
		FreeTier:     "1M requests/month, 400K GB-seconds",
		Equivalents:  map[CloudProvider]string{GCP: "Cloud Functions", Azure: "Azure Functions", Alibaba: "Function Compute"},
		Tags:         []string{"serverless", "functions", "faas"},
	})
	kb.Add(CloudService{
		Name:         "S3",
		Provider:     AWS,
		Category:     CatStorage,
		Description:  "Simple Storage Service — scalable object storage",
		UseCases:     []string{"static website hosting", "data lake", "backups", "media storage"},
		AntiPatterns: []string{"using as a database", "storing secrets without encryption"},
		PricingModel: "per-gb",
		FreeTier:     "5 GB standard storage for 12 months",
		Equivalents:  map[CloudProvider]string{GCP: "Cloud Storage", Azure: "Blob Storage", Alibaba: "OSS"},
		Tags:         []string{"storage", "object", "s3", "blob"},
	})
	kb.Add(CloudService{
		Name:         "RDS",
		Provider:     AWS,
		Category:     CatDatabase,
		Description:  "Relational Database Service — managed SQL databases",
		UseCases:     []string{"OLTP workloads", "web applications", "ERP systems"},
		AntiPatterns: []string{"using for analytics (use Redshift)", "unoptimized queries on large datasets"},
		PricingModel: "per-hour",
		FreeTier:     "750 hrs/month db.t2.micro for 12 months",
		Equivalents:  map[CloudProvider]string{GCP: "Cloud SQL", Azure: "Azure SQL", Alibaba: "ApsaraDB RDS"},
		Tags:         []string{"database", "sql", "relational", "mysql", "postgres"},
	})
	kb.Add(CloudService{
		Name:         "Aurora",
		Provider:     AWS,
		Category:     CatDatabase,
		Description:  "MySQL/PostgreSQL-compatible relational database with 5x performance",
		UseCases:     []string{"high-performance OLTP", "SaaS backends", "enterprise applications"},
		AntiPatterns: []string{"small workloads where RDS suffices", "non-relational data"},
		PricingModel: "per-hour",
		FreeTier:     "",
		Equivalents:  map[CloudProvider]string{GCP: "Spanner", Azure: "Cosmos DB", Alibaba: "PolarDB"},
		Tags:         []string{"database", "sql", "aurora", "high-performance"},
	})
	kb.Add(CloudService{
		Name:         "DynamoDB",
		Provider:     AWS,
		Category:     CatDatabase,
		Description:  "Fully managed NoSQL key-value and document database",
		UseCases:     []string{"gaming leaderboards", "session stores", "IoT data", "real-time bidding"},
		AntiPatterns: []string{"complex joins/aggregations", "ad-hoc analytics queries"},
		PricingModel: "per-request",
		FreeTier:     "25 GB storage, 25 WCU/RCU always free",
		Equivalents:  map[CloudProvider]string{GCP: "Firestore", Azure: "Cosmos DB", Alibaba: "Tair"},
		Tags:         []string{"database", "nosql", "key-value", "document"},
	})
	kb.Add(CloudService{
		Name:         "ElastiCache",
		Provider:     AWS,
		Category:     CatDatabase,
		Description:  "Managed Redis and Memcached in-memory caching",
		UseCases:     []string{"session caching", "real-time analytics", "message queues", "leaderboards"},
		AntiPatterns: []string{"persistent storage replacement", "large datasets exceeding memory"},
		PricingModel: "per-hour",
		FreeTier:     "750 hrs/month cache.t2.micro for 12 months",
		Equivalents:  map[CloudProvider]string{GCP: "Memorystore", Azure: "Cache for Redis", Alibaba: "Tair"},
		Tags:         []string{"cache", "redis", "memcached", "in-memory"},
	})
	kb.Add(CloudService{
		Name:         "ECS",
		Provider:     AWS,
		Category:     CatContainers,
		Description:  "Elastic Container Service — Docker container orchestration",
		UseCases:     []string{"microservices", "batch jobs", "CI/CD pipelines"},
		AntiPatterns: []string{"simple single-container apps (use App Runner)", "needing Kubernetes API compatibility"},
		PricingModel: "per-hour",
		FreeTier:     "",
		Equivalents:  map[CloudProvider]string{GCP: "Cloud Run", Azure: "Container Apps", Alibaba: "SAE"},
		Tags:         []string{"containers", "docker", "orchestration"},
	})
	kb.Add(CloudService{
		Name:         "EKS",
		Provider:     AWS,
		Category:     CatContainers,
		Description:  "Elastic Kubernetes Service — managed Kubernetes",
		UseCases:     []string{"Kubernetes workloads", "hybrid cloud", "multi-cloud portability"},
		AntiPatterns: []string{"simple apps not needing K8s complexity", "small teams without K8s expertise"},
		PricingModel: "per-hour",
		FreeTier:     "",
		Equivalents:  map[CloudProvider]string{GCP: "GKE", Azure: "AKS", Alibaba: "ACK"},
		Tags:         []string{"kubernetes", "k8s", "containers", "orchestration"},
	})
	kb.Add(CloudService{
		Name:         "Fargate",
		Provider:     AWS,
		Category:     CatContainers,
		Description:  "Serverless compute for containers — no server management",
		UseCases:     []string{"serverless containers", "batch processing", "microservices"},
		AntiPatterns: []string{"GPU workloads", "workloads needing host-level access"},
		PricingModel: "per-hour",
		FreeTier:     "",
		Equivalents:  map[CloudProvider]string{GCP: "Cloud Run", Azure: "Container Apps"},
		Tags:         []string{"serverless", "containers", "fargate"},
	})
	kb.Add(CloudService{
		Name:         "API Gateway",
		Provider:     AWS,
		Category:     CatNetworking,
		Description:  "Managed API creation, publishing, and security",
		UseCases:     []string{"REST APIs", "WebSocket APIs", "API versioning", "rate limiting"},
		AntiPatterns: []string{"high-throughput internal service-to-service calls", "simple static proxying"},
		PricingModel: "per-request",
		FreeTier:     "1M API calls/month for 12 months",
		Equivalents:  map[CloudProvider]string{GCP: "Apigee", Azure: "API Management", Alibaba: "API Gateway"},
		Tags:         []string{"api", "gateway", "rest", "networking"},
	})
	kb.Add(CloudService{
		Name:         "CloudFront",
		Provider:     AWS,
		Category:     CatNetworking,
		Description:  "Global content delivery network (CDN)",
		UseCases:     []string{"static asset delivery", "video streaming", "API acceleration"},
		AntiPatterns: []string{"frequently changing content without invalidation strategy"},
		PricingModel: "per-gb",
		FreeTier:     "1 TB data transfer out/month for 12 months",
		Equivalents:  map[CloudProvider]string{GCP: "Cloud CDN", Azure: "Azure CDN", Alibaba: "CDN"},
		Tags:         []string{"cdn", "content-delivery", "edge"},
	})
	kb.Add(CloudService{
		Name:         "Route 53",
		Provider:     AWS,
		Category:     CatNetworking,
		Description:  "Scalable DNS and domain name registration",
		UseCases:     []string{"domain management", "traffic routing", "health checks"},
		AntiPatterns: []string{"using for complex load balancing (use ALB/NLB)"},
		PricingModel: "per-request",
		FreeTier:     "",
		Equivalents:  map[CloudProvider]string{GCP: "Cloud DNS", Azure: "Azure DNS", Alibaba: "DNS"},
		Tags:         []string{"dns", "domain", "routing"},
	})
	kb.Add(CloudService{
		Name:         "VPC",
		Provider:     AWS,
		Category:     CatNetworking,
		Description:  "Virtual Private Cloud — isolated network environment",
		UseCases:     []string{"network isolation", "hybrid connectivity", "multi-tier architectures"},
		AntiPatterns: []string{"overly complex CIDR schemes", "single large subnet for everything"},
		PricingModel: "per-hour",
		FreeTier:     "VPC itself is free; NAT Gateway and endpoints cost",
		Equivalents:  map[CloudProvider]string{GCP: "VPC", Azure: "VNet", Alibaba: "VPC"},
		Tags:         []string{"network", "vpc", "isolation", "subnets"},
	})
	kb.Add(CloudService{
		Name:         "IAM",
		Provider:     AWS,
		Category:     CatIdentity,
		Description:  "Identity and Access Management — users, roles, policies",
		UseCases:     []string{"access control", "service roles", "cross-account access", "federation"},
		AntiPatterns: []string{"overly permissive policies", "using root account for daily operations"},
		PricingModel: "per-unit",
		FreeTier:     "Always free",
		Equivalents:  map[CloudProvider]string{GCP: "IAM", Azure: "Entra ID", Alibaba: "RAM"},
		Tags:         []string{"identity", "access", "iam", "rbac", "security"},
	})
	kb.Add(CloudService{
		Name:         "SQS",
		Provider:     AWS,
		Category:     CatMessaging,
		Description:  "Simple Queue Service — fully managed message queues",
		UseCases:     []string{"decoupling microservices", "work queues", "buffering"},
		AntiPatterns: []string{"real-time streaming (use Kinesis)", "pub/sub fan-out (use SNS)"},
		PricingModel: "per-request",
		FreeTier:     "1M requests/month always free",
		Equivalents:  map[CloudProvider]string{GCP: "Pub/Sub", Azure: "Service Bus", Alibaba: "Message Queue"},
		Tags:         []string{"messaging", "queue", "async"},
	})
	kb.Add(CloudService{
		Name:         "SNS",
		Provider:     AWS,
		Category:     CatMessaging,
		Description:  "Simple Notification Service — pub/sub messaging and notifications",
		UseCases:     []string{"fan-out notifications", "mobile push", "email/SMS alerts"},
		AntiPatterns: []string{"reliable queue processing (use SQS)", "large payload delivery"},
		PricingModel: "per-request",
		FreeTier:     "1M publishes/month for 12 months",
		Equivalents:  map[CloudProvider]string{GCP: "Pub/Sub", Azure: "Event Grid", Alibaba: "Message Queue"},
		Tags:         []string{"messaging", "pubsub", "notifications"},
	})
	kb.Add(CloudService{
		Name:         "Kinesis",
		Provider:     AWS,
		Category:     CatAnalytics,
		Description:  "Real-time data streaming at scale",
		UseCases:     []string{"log aggregation", "real-time analytics", "IoT telemetry", "clickstream"},
		AntiPatterns: []string{"small-scale messaging (use SQS)", "batch-only workloads"},
		PricingModel: "per-hour",
		FreeTier:     "",
		Equivalents:  map[CloudProvider]string{GCP: "Dataflow", Azure: "Event Hubs", Alibaba: "Message Queue"},
		Tags:         []string{"streaming", "real-time", "analytics"},
	})
	kb.Add(CloudService{
		Name:         "Athena",
		Provider:     AWS,
		Category:     CatAnalytics,
		Description:  "Serverless interactive SQL query service for S3 data",
		UseCases:     []string{"ad-hoc analytics", "log analysis", "data lake queries"},
		AntiPatterns: []string{"high-concurrency OLTP", "repeatedly scanning same data (use Redshift)"},
		PricingModel: "per-gb",
		FreeTier:     "",
		Equivalents:  map[CloudProvider]string{GCP: "BigQuery", Azure: "Synapse", Alibaba: "MaxCompute"},
		Tags:         []string{"analytics", "sql", "query", "serverless"},
	})
	kb.Add(CloudService{
		Name:         "Redshift",
		Provider:     AWS,
		Category:     CatAnalytics,
		Description:  "Petabyte-scale cloud data warehouse",
		UseCases:     []string{"business intelligence", "data warehousing", "ETL pipelines"},
		AntiPatterns: []string{"OLTP workloads", "small datasets under 100 GB"},
		PricingModel: "per-hour",
		FreeTier:     "2-month free trial (DC2.Large)",
		Equivalents:  map[CloudProvider]string{GCP: "BigQuery", Azure: "Synapse", Alibaba: "MaxCompute"},
		Tags:         []string{"analytics", "data-warehouse", "bi"},
	})
	kb.Add(CloudService{
		Name:         "SageMaker",
		Provider:     AWS,
		Category:     CatAI_ML,
		Description:  "Fully managed ML platform — build, train, deploy models",
		UseCases:     []string{"ML model training", "inference endpoints", "MLOps pipelines"},
		AntiPatterns: []string{"simple inference (use Bedrock)", "non-ML compute tasks"},
		PricingModel: "per-hour",
		FreeTier:     "250 hrs/month t2.medium notebook for 2 months",
		Equivalents:  map[CloudProvider]string{GCP: "Vertex AI", Azure: "Azure OpenAI", Alibaba: "DashScope"},
		Tags:         []string{"ml", "ai", "training", "inference"},
	})
	kb.Add(CloudService{
		Name:         "Bedrock",
		Provider:     AWS,
		Category:     CatAI_ML,
		Description:  "Managed foundation model access (Claude, Llama, Titan, etc.)",
		UseCases:     []string{"generative AI apps", "RAG pipelines", "text generation", "embeddings"},
		AntiPatterns: []string{"custom model training (use SageMaker)", "non-AI workloads"},
		PricingModel: "per-request",
		FreeTier:     "",
		Equivalents:  map[CloudProvider]string{GCP: "Vertex AI", Azure: "Azure OpenAI", Alibaba: "DashScope"},
		Tags:         []string{"ai", "llm", "foundation-models", "generative-ai"},
	})
	kb.Add(CloudService{
		Name:         "CloudWatch",
		Provider:     AWS,
		Category:     CatMonitoring,
		Description:  "Monitoring and observability — metrics, logs, alarms",
		UseCases:     []string{"infrastructure monitoring", "log aggregation", "alerting", "dashboards"},
		AntiPatterns: []string{"complex APM (consider Datadog/New Relic)", "long-term log storage (use S3)"},
		PricingModel: "per-unit",
		FreeTier:     "10 custom metrics, 5 GB log ingestion/month",
		Equivalents:  map[CloudProvider]string{GCP: "Cloud Monitoring", Azure: "Azure Monitor", Alibaba: "CloudMonitor"},
		Tags:         []string{"monitoring", "observability", "logs", "metrics", "alarms"},
	})
	kb.Add(CloudService{
		Name:         "CodePipeline",
		Provider:     AWS,
		Category:     CatDevTools,
		Description:  "Continuous delivery pipeline for build, test, deploy",
		UseCases:     []string{"CI/CD automation", "release management", "multi-stage deployments"},
		AntiPatterns: []string{"complex build logic (use CodeBuild directly)", "non-AWS targets"},
		PricingModel: "per-unit",
		FreeTier:     "1 active pipeline/month always free",
		Equivalents:  map[CloudProvider]string{GCP: "Cloud Build", Azure: "Azure DevOps", Alibaba: "ARMS"},
		Tags:         []string{"ci-cd", "devops", "pipeline", "deployment"},
	})
	kb.Add(CloudService{
		Name:         "EventBridge",
		Provider:     AWS,
		Category:     CatServerless,
		Description:  "Serverless event bus for application integration",
		UseCases:     []string{"event-driven architectures", "SaaS integration", "scheduled events"},
		AntiPatterns: []string{"high-throughput streaming (use Kinesis)", "synchronous request-response"},
		PricingModel: "per-request",
		FreeTier:     "All AWS service events free",
		Equivalents:  map[CloudProvider]string{GCP: "Eventarc", Azure: "Event Grid", Alibaba: "Message Queue"},
		Tags:         []string{"events", "serverless", "integration", "event-driven"},
	})
	kb.Add(CloudService{
		Name:         "Step Functions",
		Provider:     AWS,
		Category:     CatServerless,
		Description:  "Serverless workflow orchestration with visual state machines",
		UseCases:     []string{"multi-step workflows", "ETL orchestration", "saga patterns", "approval flows"},
		AntiPatterns: []string{"simple sequential calls", "high-frequency low-latency pipelines"},
		PricingModel: "per-request",
		FreeTier:     "4000 state transitions/month always free",
		Equivalents:  map[CloudProvider]string{GCP: "Cloud Workflows", Azure: "Logic Apps"},
		Tags:         []string{"workflow", "orchestration", "serverless", "state-machine"},
	})
	kb.Add(CloudService{
		Name:         "Secrets Manager",
		Provider:     AWS,
		Category:     CatSecurity,
		Description:  "Securely store and rotate secrets, API keys, credentials",
		UseCases:     []string{"database credential rotation", "API key management", "certificate storage"},
		AntiPatterns: []string{"storing large config files", "non-secret configuration (use Parameter Store)"},
		PricingModel: "per-unit",
		FreeTier:     "30-day free trial",
		Equivalents:  map[CloudProvider]string{GCP: "Secret Manager", Azure: "Key Vault", Alibaba: "KMS"},
		Tags:         []string{"security", "secrets", "credentials", "rotation"},
	})
	kb.Add(CloudService{
		Name:         "KMS",
		Provider:     AWS,
		Category:     CatSecurity,
		Description:  "Key Management Service — create and manage encryption keys",
		UseCases:     []string{"data encryption", "envelope encryption", "digital signing"},
		AntiPatterns: []string{"storing secrets (use Secrets Manager)", "client-side crypto without HSM needs"},
		PricingModel: "per-request",
		FreeTier:     "20K requests/month always free",
		Equivalents:  map[CloudProvider]string{GCP: "Cloud KMS", Azure: "Key Vault", Alibaba: "KMS"},
		Tags:         []string{"security", "encryption", "keys", "kms"},
	})
	kb.Add(CloudService{
		Name:         "WAF",
		Provider:     AWS,
		Category:     CatSecurity,
		Description:  "Web Application Firewall — protect against web exploits",
		UseCases:     []string{"SQL injection protection", "XSS prevention", "bot mitigation", "rate limiting"},
		AntiPatterns: []string{"replacing network firewall", "DDoS protection alone (use Shield)"},
		PricingModel: "per-request",
		FreeTier:     "",
		Equivalents:  map[CloudProvider]string{GCP: "Cloud Armor", Azure: "Azure Firewall", Alibaba: "Web App Firewall"},
		Tags:         []string{"security", "waf", "firewall", "web-protection"},
	})
	kb.Add(CloudService{
		Name:         "GuardDuty",
		Provider:     AWS,
		Category:     CatSecurity,
		Description:  "Intelligent threat detection using ML-based anomaly detection",
		UseCases:     []string{"threat detection", "anomaly monitoring", "compliance", "account compromise detection"},
		AntiPatterns: []string{"replacing SIEM", "application-level security scanning"},
		PricingModel: "per-gb",
		FreeTier:     "30-day free trial",
		Equivalents:  map[CloudProvider]string{GCP: "Security Command Center", Azure: "Microsoft Defender"},
		Tags:         []string{"security", "threat-detection", "monitoring"},
	})
}
