version: 2

project_name: blackcat

before:
  hooks:
    - go mod tidy

builds:
  - id: blackcat
    main: ./cmd/blackcat/
    binary: blackcat
    env:
      - CGO_ENABLED=1
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.ShortCommit}}
    overrides:
      - goos: linux
        goarch: amd64
        env:
          - CC=zig cc -target x86_64-linux-gnu
      - goos: linux
        goarch: arm64
        env:
          - CC=zig cc -target aarch64-linux-gnu
      - goos: darwin
        goarch: amd64
        env:
          - CC=zig cc -target x86_64-macos
      - goos: darwin
        goarch: arm64
        env:
          - CC=zig cc -target aarch64-macos

archives:
  - id: default
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - configs/default.yaml

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"

release:
  github:
    owner: meowai
    name: blackcat
  draft: false
  prerelease: auto
  name_template: "BlackCat v{{.Version}}"
